apps/idr_idm/urls.py
from django.urls import path
from . import views

app_name = 'idr_idm'
urlpatterns = [
    # path('home/', views.index, name='index'),
    path('', views.index, name='index'),

    path('post-line-data/', views.post_line, name='post_line'),
    path('update-line-data/', views.update_line, name='update_line'),
    path('create-machine/', views.create_machine, name='create_machine'),
    path('get-all-machines-in-table/', views.get_all_machines_in_table, name='get_all_machines_in_table'),
    path('get-all-matriculate/', views.get_all_matriculate, name='get_all_matriculate'),
    path('get-all-localisation/', views.gat_all_localisation, name='gat_all_localisation'),
    path('get-all-breakdown/', views.get_all_breakdown, name='get_all_breakdown'),
    path('file-upload/', views.upload_file, name='upload_file'),
    path('get-file-jointe/', views.get_file_jointe, name='get_file_jointe'),
    path('delete-file-jointe/', views.delete_jointe, name='delete_jointe'),
    path('delete-breakdown/', views.delete_breakdown, name='delete_breakdown'),
    path('get-machines/', views.get_machines, name='get_machines'),
    path('get-breakdown/', views.get_all_machineidridm_with_breakdown_false, name='get_breakdown'),
    path('get-all-client/', views.get_all_client, name='get_all_client'),
    path('add-client/', views.add_client, name='add_client'),
    path('delete-client/<str:uid>/', views.delete_client, name='delete_client'),
    path('details/<str:uid>/', views.detail, name='details'),
    path('download/', views.download_file, name='download_file'),

]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('guard.urls')),
    path("custome-accounts/", include("allauth.urls")),  # new
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('apps.idr_idm.urls')),
    re_path(r"^static/(?P<path>.*)$", serve, {'document_root': settings.STATIC_ROOT}),
    re_path(r"^media/(?P<path>.*)$", serve, {'document_root': settings.MEDIA_ROOT}),
    path("__reload__/", include("django_browser_reload.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]
urlpatterns += staticfiles_urlpatterns()

guard/urls.py
from django.urls import path

from . import views

app_name = 'guard'
urlpatterns = [
    path('login/', views.LoginLDAP.as_view(), name='login'),
    path('logout/', views.logout_ldap, name='logout'),
    path('administrations/', views.index, name='index'),
    path('get-all-permission/', views.get_all_permission, name='get_all_permission'),
    path('administrations/get-all-users/', views.all_users_json, name='get_all_users_json'),
    path('administrations/get-all-client-not-used/', views.get_all_client_not_used_json,
         name='get_all_client_not_used_json'),
    path('administrations/get-all-client-used/', views.get_all_client_used_json, name='get_all_client_used_json'),
    path('administrations/update-status-client/', views.update_status_client, name='update_status_client'),
    path('administrations/update-user/', views.update_user_json, name='update_user_json'),
    path('administrations/create-user/', views.create_user_json, name='create_user_json'),
    path('administrations/delete-user/', views.delete_user_json, name='delete_user_json'),
]

templates/partials/_modal_add_machine.html
<div class="modal fade" id="addCompanyModal" tabindex="-1" aria-labelledby="addCompanyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCompanyModalLabel">Ajout</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" action="{% url 'apps:create_machine' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-row">
                        <div class="col">
                            <div class="form-group">
                                <label for="{{ form_add_machine.model.id_for_label }}" class="col-form-label">{{ form_add_machine.model.label }}
                            <code>*</code></label>
                        {{ form_add_machine.model }}
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                <label for="{{ form_add_machine.matriculate.id_for_label }}"
                                       class="col-form-label">{{ form_add_machine.matriculate.label }} <code>*</code></label>
                                {{ form_add_machine.matriculate }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="{{ form_add_machine.description.id_for_label }}"
                               class="col-form-label">{{ form_add_machine.description.label }}</label>
                        {{ form_add_machine.description }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/partials/_modal_client.html
<div id="addClientModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="POST" class="needs-validation" action="{% url 'app:add-client' %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h4 class="modal-title">Ajout de Client</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="client_form.group">
                        {{ client_form.client_name.label_tag }}
                        {{ client_form.client_name }}
                        <div class="invalid-feedback">Nom du client requis.</div>
                    </div>
                    <div class="client_form.group">
                        {{ client_form.email.label_tag }}
                        {{ client_form.email }}
                        <div class="invalid-feedback">Email invalide.</div>
                    </div>
                    <div class="client_form.group ">
                        {{ client_form.address.label_tag }}
                        {{ client_form.address }}
                        <div class="invalid-feedback">Adresse requise.</div>
                    </div>
                    <div class="client_form.group">
                        {{ client_form.phone.label_tag }}
                        {{ client_form.phone }}
                        <div class="invalid-feedback">Numéro de téléphone requis.</div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
                    <button type="submit" class="btn btn-success">Ajouter</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/partials/_modal_list_machine.html
<div class="modal fade" id="listMachineModal" tabindex="-1" aria-labelledby="listMachineModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="listMachineModalLabel">List des Machines Restant</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="display nowrap" id="tableMachine" style="width: 100%">
                    <thead>
                    <tr>
                        <th>N°</th>
                        <th>Matricule</th>
                        <th>Model</th>
                    </tr>
                    </thead>
                </table>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-secondary">Fermer</button>
            </div>
        </div>
    </div>
</div>

templates/partials/_modal_map.html
<div class="modal fade" id="chartModal" data-backdrop="static" data-keyboard="false" tabindex="-1"
     aria-labelledby="chartModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="chartModalLabel">Coordonnée des engins</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="container-map" style="width: 100%; height: 400px;"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'idr_idm:index' %}">
        <img src="{% static 'img/ID Rental.svg' %}" width="30" height="30" class="d-inline-block align-top" alt=""
             loading="lazy">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if path == '/' %}active{% endif %}">
                <a class="nav-link" href="{% url 'idr_idm:index' %}">GLOBAL <span
                        class="sr-only">(current)</span></a>
            </li>
            {% for nav in navs %}
                <li class="nav-item {% if uid_client == nav.uid %}active{% endif %}">
                    <a class="nav-link" href="{% url 'idr_idm:details' nav.uid %}"><i class="fas fa-star text-warning"></i>
                        IDR-{{ nav.name|upper }}</a>
                </li>
            {% endfor %}
            {% if user.is_staff %}
                <li class="nav-item {% if path == '/accounts/administrations/' %}active{% endif %} disabled" disabled>
                    <a class="nav-link " href="{% url 'guard:index' %}" tabindex="-1">Administration</a>
                </li>
            {% endif %}
        </ul>
        <div class="btn text-white">
            <i class="fas fa-user " title=""></i> ({{ user.username }})
        </div>
        <div class="navbar-text d-flex my-2 my-lg-0">
            <a href="{% url 'guard:logout' %}" class="btn btn-outline-danger ml-1 my-2 my-sm-0">Déconnecter</a>
        </div>
    </div>
</nav>